targets:
  $default:
    builders:
      generators|annotations:
        enabled: true

builders:
  generators:
    target: ":builder_generator"
    # 1
    import: "package:builder_generator/builder_generator.dart"
    # 2
    builder_factories: ["generate"]
    # 3
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]