name: builder_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  build:
  source_gen:
  builder:
    path: ../builder
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner:
